In [101]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency
from IPython.display import display

from preparar_dados import criar_dados_descritivos

pd.set_option("display.max_columns", 180)
pd.set_option("display.max_rows", 300)
pd.set_option("display.float_format", lambda valor: f"{valor:,.3f}")

arquivo_2019 = "pns2019.csv"

In [102]:
base = pd.read_csv(arquivo_2019)

display(base.head())
display(base.shape)

,V0001,V0024,UPA_PNS,V0006_PNS,V0015,V0020,V0022,V0026,V0031,V0025A,V0025B,A001,A002010,A003010,A004010,A01001,A011,A005010,A005012,A00601,A009010,A01401,A01402,A01403,A01501,A016010,A018011,A018012,A018013,A018014,A018015,A018016,A018017,A018018,A018019,A018020,A018021,A018022,A018023,A018024,A018025,A018026,A018027,A018028,A01901,A02101,A02102,A02201,A02305,A02306,A02307,A02308,A02401,A02402,B001,B002,B003,B004,C001,C00301,C004,C006,C00701,C00702,C00703,C008,C009,C01001,C010010,C013,C014,C015,C016,C017,C018,C01801,C011,C012,D001,D00201,D00202,D00301,D00501,D006,D00601,D007,D008,D00901,D010,D01101,...,V034,V03501,V03502,V03503,V036,V037,V038,V039,T001,T002,T003,T004,T005,T00601,T00602,T00603,T00604,T00605,T00606,Y001,Y00101,Y002,Y003,Y004,Y005,Y006,Y007,H001,H002,H003,H004,H005,H006,H007,H008,H009,H010,H011,H012,H013,H014,H015,H016,H017,H018,H019,H020,H021,H022,H023,H024,H025,H026,H027,H028,H029,H030,W001,W00101,W00102,W00103,W00201,W00202,W00203,V0028,V0029,V0030,V00281,V00291,V00301,V00282,V00292,V00302,V00283,V00293,V00303,VDC001,VDC003,VDD004A,VDE001,VDE002,VDE014,VDF002,VDF003,VDF004,VDL001,VDM001,VDP001,VDR001,VDDATA
0,11,1110011,110000016,1,1,2019,6.000,1,1,1.000,NaN,1.000,1.000,1.000,1.000,5.000,2.000,1.000,NaN,1.000,1.000,2.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,0.000,2.000,0.000,0.000,NaN,0.000,1.000,4.000,4.000,5.000,6.000,1.000,1.000,2.000,22.000,11.000,"1,963.000",55.000,1.000,1.000,2.000,NaN,2.000,1.000,2.000,NaN,1.000,17.000,1.000,1.000,1.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,1.000,5.000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,2.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000,17.000,1.000,3.000,NaN,2.000,3.000,1.000,2.000,2.000,2.000,1.000,1.000,1.000,1.000,1.000,1.000,3.000,4.000,4.000,4.000,1.000,2.000,NaN,NaN,NaN,NaN,1.000,1.000,1.000,1.000,4.000,4.000,4.000,4.000,1.000,4.000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,256.767,NaN,118.312,368.875,NaN,"529,479.000","69,788.655",NaN,111.000,"11,124.000",NaN,6.000,3.000,2.000,1.000,1.000,6.000,"2,098.000",350.000,2.000,NaN,NaN,NaN,NaN,20210825
1,11,1110011,110000016,1,1,2019,6.000,1,1,0.000,NaN,1.000,1.000,1.000,1.000,5.000,2.000,1.000,NaN,1.000,1.000,2.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,0.000,2.000,0.000,0.000,NaN,0.000,1.000,4.000,4.000,5.000,6.000,2.000,2.000,1.000,8.000,4.000,"1,950.000",69.000,4.000,1.000,1.000,NaN,2.000,1.000,2.000,NaN,1.000,30.000,1.000,2.000,1.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,2.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,NaN,NaN,118.312,NaN,NaN,"529,479.000",NaN,NaN,111.000,NaN,NaN,6.000,3.000,1.000,2.000,NaN,NaN,"2,098.000",350.000,2.000,NaN,NaN,NaN,NaN,20210825
2,11,1110011,110000016,1,1,2019,6.000,1,1,0.000,NaN,1.000,1.000,1.000,1.000,5.000,2.000,1.000,NaN,1.000,1.000,2.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,0.000,2.000,0.000,0.000,NaN,0.000,1.000,4.000,4.000,5.000,6.000,3.000,6.000,1.000,13.000,9.000,"1,987.000",31.000,2.000,2.000,NaN,2.000,NaN,NaN,NaN,1.000,2.000,NaN,4.000,2.000,1.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,1.000,10.000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,NaN,NaN,118.312,NaN,NaN,"529,479.000",NaN,NaN,111.000,NaN,NaN,6.000,3.000,5.000,1.000,1.000,4.000,"2,098.000",350.000,2.000,NaN,NaN,NaN,NaN,20210825
3,11,1110011,110000016,1,1,2019,6.000,1,1,9.000,NaN,1.000,1.000,1.000,1.000,5.000,2.000,1.000,NaN,1.000,1.000,2.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,0.000,2.000,0.000,0.000,NaN,0.000,1.000,4.000,4.000,5.000,6.000,4.000,10.000,1.000,99.000,99.000,"9,999.000",9.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,1.000,1.000,2.000,4.000,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,NaN,NaN,118.312,NaN,NaN,"529,479.000",NaN,NaN,111.000,NaN,NaN,6.000,3.000,1.000,NaN,NaN,NaN,"2,098.000",350.000,2.000,NaN,NaN,NaN,NaN,20210825
4,11,1110011,110000016,1,1,2019,6.000,1,1,9.000,NaN,1.000,1.000,1.000,1.000,5.000,2.000,1.000,NaN,1.000,1.000,2.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,0.000,2.000,0.000,0.000,NaN,0.000,1.000,4.000,4.000,5.000,6.000,5.000,10.000,2.000,99.000,99.000,"9,999.000",6.000,4.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,1.000,1.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,NaN,NaN,118.312,NaN,NaN,"529,479.000",NaN,NaN,111.000,NaN,NaN,6.000,3.000,1.000,NaN,NaN,NaN,"2,098.000",350.000,2.000,NaN,NaN,NaN,NaN,20210825

(293726, 1087)

In [103]:
base_adultos = base[(base["V0025A"] == 1) & (base["C008"] >= 18) ]

display(base_adultos.shape)
display(base_adultos.head())

(91683, 1087)

,V0001,V0024,UPA_PNS,V0006_PNS,V0015,V0020,V0022,V0026,V0031,V0025A,V0025B,A001,A002010,A003010,A004010,A01001,A011,A005010,A005012,A00601,A009010,A01401,A01402,A01403,A01501,A016010,A018011,A018012,A018013,A018014,A018015,A018016,A018017,A018018,A018019,A018020,A018021,A018022,A018023,A018024,A018025,A018026,A018027,A018028,A01901,A02101,A02102,A02201,A02305,A02306,A02307,A02308,A02401,A02402,B001,B002,B003,B004,C001,C00301,C004,C006,C00701,C00702,C00703,C008,C009,C01001,C010010,C013,C014,C015,C016,C017,C018,C01801,C011,C012,D001,D00201,D00202,D00301,D00501,D006,D00601,D007,D008,D00901,D010,D01101,...,V034,V03501,V03502,V03503,V036,V037,V038,V039,T001,T002,T003,T004,T005,T00601,T00602,T00603,T00604,T00605,T00606,Y001,Y00101,Y002,Y003,Y004,Y005,Y006,Y007,H001,H002,H003,H004,H005,H006,H007,H008,H009,H010,H011,H012,H013,H014,H015,H016,H017,H018,H019,H020,H021,H022,H023,H024,H025,H026,H027,H028,H029,H030,W001,W00101,W00102,W00103,W00201,W00202,W00203,V0028,V0029,V0030,V00281,V00291,V00301,V00282,V00292,V00302,V00283,V00293,V00303,VDC001,VDC003,VDD004A,VDE001,VDE002,VDE014,VDF002,VDF003,VDF004,VDL001,VDM001,VDP001,VDR001,VDDATA
0,11,1110011,110000016,1,1,2019,6.000,1,1,1.000,NaN,1.000,1.000,1.000,1.000,5.000,2.000,1.000,NaN,1.000,1.000,2.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,0.000,2.000,0.000,0.000,NaN,0.000,1.000,4.000,4.000,5.000,6.000,1.000,1.000,2.000,22.000,11.000,"1,963.000",55.000,1.000,1.000,2.000,NaN,2.000,1.000,2.000,NaN,1.000,17.000,1.000,1.000,1.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,1.000,5.000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,2.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000,17.000,1.000,3.000,NaN,2.000,3.000,1.000,2.000,2.000,2.000,1.000,1.000,1.000,1.000,1.000,1.000,3.000,4.000,4.000,4.000,1.000,2.000,NaN,NaN,NaN,NaN,1.000,1.000,1.000,1.000,4.000,4.000,4.000,4.000,1.000,4.000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,256.767,NaN,118.312,368.875,NaN,"529,479.000","69,788.655",NaN,111.000,"11,124.000",NaN,6.000,3.000,2.000,1.000,1.000,6.000,"2,098.000",350.000,2.000,NaN,NaN,NaN,NaN,20210825
9,11,1110011,110000016,2,1,2019,4.000,1,1,1.000,NaN,1.000,1.000,1.000,1.000,4.000,3.000,3.000,2.000,1.000,5.000,1.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,3.000,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,1.000,0.000,0.000,0.000,1.000,NaN,1.000,4.000,5.000,5.000,4.000,4.000,5.000,2.000,27.000,2.000,"2,000.000",19.000,4.000,2.000,NaN,2.000,NaN,NaN,NaN,2.000,NaN,NaN,4.000,2.000,1.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,1.000,10.000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,2.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000,NaN,3.000,NaN,NaN,NaN,NaN,NaN,3.000,2.000,4.000,8.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,342.356,NaN,118.312,508.107,NaN,"529,479.000","27,709.937",NaN,111.000,"11,122.000",NaN,4.000,4.000,4.000,1.000,1.000,6.000,"1,000.000",250.000,2.000,NaN,NaN,NaN,NaN,20210825
10,11,1110011,110000016,3,1,2019,8.000,1,1,1.000,NaN,1.000,1.000,1.000,1.000,8.000,4.000,1.000,NaN,1.000,1.000,4.000,NaN,NaN,4.000,1.000,1.000,3.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,3.000,1.000,1.000,2.000,NaN,1.000,2.000,2.000,NaN,1.000,2.000,NaN,1.000,1.000,1.000,0.000,0.000,1.000,1.000,1.000,4.000,4.000,5.000,8.000,1.000,1.000,2.000,27.000,11.000,"1,973.000",45.000,2.000,2.000,NaN,2.000,NaN,NaN,NaN,1.000,1.000,18.000,4.000,1.000,1.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,1.000,10.000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,2.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000,17.000,1.000,1.000,1.000,NaN,3.000,1.000,4.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,427.945,NaN,118.312,614.792,NaN,"529,479.000","69,788.655",NaN,111.000,"11,124.000",NaN,8.000,5.000,5.000,1.000,1.000,9.000,"4,000.000",500.000,3.000,NaN,4.000,NaN,1.000,20210825
18,11,1110011,110000016,4,1,2019,1.000,1,1,1.000,NaN,1.000,1.000,1.000,3.000,1.000,1.000,1.000,NaN,1.000,6.000,0.000,1.000,NaN,4.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,2.000,NaN,1.000,1.000,2.000,NaN,2.000,NaN,2.000,NaN,2.000,NaN,1.000,2.000,NaN,1.000,0.000,1.000,0.000,0.000,NaN,0.000,1.000,4.000,5.000,5.000,1.000,1.000,1.000,2.000,30.000,8.000,"1,960.000",58.000,2.000,2.000,NaN,2.000,NaN,NaN,NaN,1.000,2.000,NaN,3.000,1.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,1.000,4.000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,2.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000,NaN,3.000,NaN,NaN,NaN,NaN,NaN,4.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,85.589,NaN,118.312,122.958,NaN,"529,479.000","69,788.655",NaN,111.000,"11,124.000",NaN,1.000,1.000,1.000,1.000,1.000,7.000,324.000,324.000,2.000,NaN,1.000,NaN,NaN,20210825
19,11,1110011,110000016,5,1,2019,2.000,1,1,1.000,NaN,2.000,1.000,1.000,1.000,2.000,1.000,1.000,NaN,1.000,6.000,1.000,NaN,NaN,4.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,NaN,1.000,2.000,NaN,2.000,NaN,NaN,NaN,NaN,NaN,NaN,1.000,3.000,5.000,5.000,2.000,1.000,1.000,2.000,30.000,7.000,"1,990.000",28.000,4.000,2.000,NaN,2.000,NaN,NaN,NaN,1.000,1.000,20.000,4.000,1.000,1.000,1.000,1.000,8.000,1.000,6.000,NaN,2.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,2.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000,NaN,3.000,NaN,NaN,NaN,NaN,NaN,3.000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.589,85.589,NaN,118.312,121.285,NaN,"529,479.000","68,501.612",NaN,111.000,"11,123.000",NaN,2.000,1.000,6.000,2.000,NaN,NaN,0.000,0.000,1.000,NaN,NaN,NaN,NaN,20210825

## Todas as variáveis selecionadas

In [ ]:
grupos_originais = {
    "Essenciais": [
            "Q092", "V0025A", "V00291",
        ],

    "Demográficas e territoriais": [
        "V0001", "V0026", "C006", "C008",
        "C009", "C01001", "C011",
    ],
    "Socioeconômicas e trabalho": [
        "VDD004A", "VDF003", "VDF004",
        "VDE001", "VDE002", "E001", "E017", "E033",
    ],
    "Domicílio": [
        "A01401", "A01501", "A016010", "A01901",
    ],
    "Apoio social": [
        "M01401", "M01501", "M01601",
        "M01701", "M01801", "M01901",
    ],
    "Acesso à saúde": [
        "B001", "B003", "I00102", "J001", "J037",
    ],
    "Álcool, atividade física e tabaco": [
        "P029", "P034", "P035", "P036", "P03701", "P050",
    ],
    "Violência psicológica": [
        "V00201", "V00202", "V00203", "V00204", "V00205",
    ],
    "Violência física": [
        "V01401", "V01402", "V01403", "V01404", "V01405",
    ],
    "Violência sexual": [
        "V02701", "V02702",
    ],
    "Saúde geral e comorbidades": [
        "N001", "Q00201", "Q03001", "Q060", "Q06306",
        "Q068", "Q074", "Q079", "Q084", "Q088", "Q11006",
    ],
    "Itens_PHQ-9": [
        "N010", "N011", "N012", "N013", "N014", "N015",
        "N016", "N017", "N018",
    ]
}

variaveis = []

for lista in grupos_originais.values():
    for item in lista:
        variaveis.append(item)

dados = base_adultos[variaveis]

In [ ]:
for coluna in dados.columns:
    dados[coluna] = pd.to_numeric(dados[coluna], errors="coerce")

dados.shape

`Q092 = 1` representa diagnóstico autorreferido e `Q092 = 2` representa ausência de diagnóstico autorreferido.

In [ ]:
dados_descritivos, variaveis_preparadas = (
    criar_dados_descritivos(dados)
)

## Inventário final das variáveis preparadas

In [ ]:
display(dados_descritivos.head())

print(dados_descritivos.shape)
print(len(variaveis_preparadas))

print(variaveis_preparadas)

In [ ]:
linhas = []

for nome, info in variaveis_preparadas.items():
    linha = {
        "Variável preparada": nome,
        "Bloco": info["Bloco"],
        "Origem": info["Origem"],
    }

    linhas.append(linha)

inventario = pd.DataFrame(linhas)

print("Quantidade de variáveis preparadas:", len(inventario))
display(inventario)

# Análise estatística

In [ ]:
display(dados_descritivos)

In [ ]:
def prevalencia_ponderada_por_categoria(dados, variavel):
    base = dados.dropna(subset=[variavel, "Diagnóstico binário", "Peso"]).copy()
    base = base[base["Peso"] > 0]

    resultados = []

    for categoria, parte in base.groupby(variavel, observed=True): #o groupby separa a variavel nos grupos que ela tem e isso vira a categoria e os dados vira a parte tipo sexo categoria [masculino, feminino]
        percentual = np.average(parte["Diagnóstico binário"].astype(float), weights=parte["Peso"]) * 100 #transforma a tabela em float e o average faz a media ponderada

        resultados.append({
            "Categoria": categoria,
            "Participantes válidos": len(parte),
            "Diagnóstico ponderado (%)": percentual,
        })

    return pd.DataFrame(resultados)


def analisar_variavel(dados, variavel):
    base = dados[
        [
            variavel,
            "Diagnóstico de depressão",
            "Diagnóstico binário",
            "Peso",
        ]
    ].dropna(subset=[variavel, "Diagnóstico de depressão"]).copy() #dropna(subset) remove as linhas que tiverem ausentes nas colunas que passo (Variavel, Diagnostico) 

    contagem = pd.crosstab(base[variavel], base["Diagnóstico de depressão"]) #Quantas pessoas de cada categoria tem 

    percentuais = pd.crosstab(base[variavel], base["Diagnóstico de depressão"], normalize="columns") * 100 

    comparacao = percentuais.copy()

    teste = {
        "Variável": variavel,
        "Participantes válidos": len(base),
        "Qtd possiveis": contagem.shape[0], #saphe[0] mostra quantas linhas, ou seja quantas possibilidades
        "Qui-quadrado": np.nan,
        "p-valor": np.nan,
        "V de Cramér": np.nan,
    }

    if contagem.shape[0] >= 2 and contagem.shape[1] >= 2:
        chi2, p_valor, gl, esperadas = chi2_contingency(contagem)

        n = contagem.values.sum() #conta quantas participantes tem na tabela 

        menor_dimensao = min(contagem.shape[0] - 1, contagem.shape[1] - 1)

        if n > 0 and menor_dimensao > 0:
            v_cramer = np.sqrt(chi2 / (n * menor_dimensao))
        else:
            v_cramer = np.nan

        teste.update({
            "Qui-quadrado": chi2,
            "p-valor": p_valor,
            "V de Cramér": v_cramer,
        })

    return {
        "contagem": contagem,
        "percentuais": percentuais,
        "comparacao": comparacao,
        "ponderado": prevalencia_ponderada_por_categoria(
            dados,
            variavel,
        ),
        "teste": teste,
    }

In [ ]:
resultados_detalhados = {}
linhas_ranking = []

variaveis_nao_analisadas = [
    "Diagnóstico de depressão",
    "Diagnóstico binário",
    "Peso",
]

variaveis_para_analisar = inventario.loc[~inventario["Variável preparada"].isin(variaveis_nao_analisadas), "Variável preparada"]

for variavel in variaveis_para_analisar:
    resultado = analisar_variavel(
        dados_descritivos,
        variavel,
    )

    resultados_detalhados[variavel] = resultado

    linha = resultado["teste"].copy()
    linha["Bloco"] = variaveis_preparadas[variavel]["Bloco"]
    linha["Origem"] = variaveis_preparadas[variavel]["Origem"]

    linhas_ranking.append(linha)


ranking = pd.DataFrame(linhas_ranking)

colunas_ranking = [
    "Bloco",
    "Variável",
    "Origem",
    "Participantes válidos",
    "Qtd possiveis",
    "Qui-quadrado",
    "p-valor",
    "V de Cramér",
]

ranking = (
    ranking[colunas_ranking]
    .sort_values(
        "V de Cramér",
        ascending=False,
        na_position="last",
    )
    .reset_index(drop=True)
)

ranking.insert(
    0,
    "Posição",
    range(1, len(ranking) + 1),
)

display(ranking)

In [ ]:
for bloco, ranking_bloco in ranking.groupby("Bloco", sort=False):
    ranking_bloco = (ranking_bloco.sort_values("V de Cramér", ascending=False, na_position="last").reset_index(drop=True))

    ranking_bloco.insert(
        0,
        "Posição no bloco",
        range(1, len(ranking_bloco) + 1),
    )

    print("\n" + "=" * 90)
    print(bloco)
    print("=" * 90)

    display(
        ranking_bloco[
            [
                "Posição no bloco",
                "Variável",
                "Origem",
                "Participantes válidos",
                "p-valor",
                "V de Cramér",
            ]
        ]
    )

In [ ]:
maiores_percentuais = []

for variavel, resultado in resultados_detalhados.items():
    tabela = resultado["ponderado"].dropna(subset=["Diagnóstico ponderado (%)"])

    if len(tabela) == 0:
        continue

    maior = tabela.loc[tabela["Diagnóstico ponderado (%)"].idxmax()]

    maiores_percentuais.append({
        "Bloco": variaveis_preparadas[variavel]["Bloco"],
        "Variável": variavel,
        "Categoria com maior percentual": maior["Categoria"],
        "Diagnóstico ponderado (%)": maior["Diagnóstico ponderado (%)"],
        "Participantes válidos na categoria": maior["Participantes válidos"],
    })

maiores_percentuais = pd.DataFrame(maiores_percentuais).sort_values("Diagnóstico ponderado (%)", ascending=False).reset_index(drop=True)

display(maiores_percentuais)

# Ver uma variável detalhadamente

## Escolher a variável

In [ ]:
def analisar_variavel_completa(dados, variavel, variaveis_preparadas, mostrar_graficos=True):

    variaveis_tecnicas = [
        "Diagnóstico de depressão",
        "Diagnóstico binário",
        "Peso",
    ]

    if variavel in variaveis_tecnicas:
        print(f'"{variavel}" é uma variável técnica e não deve ser analisada.')
        return None

    colunas_necessarias = [
        variavel,
        "Diagnóstico de depressão",
        "Diagnóstico binário",
        "Peso",
    ]

    colunas_ausentes = []

    for coluna in colunas_necessarias:
        if coluna not in dados.columns:
            colunas_ausentes.append(coluna)

    if colunas_ausentes:
        print("Não foi possível realizar a análise.")
        print("Colunas ausentes:", colunas_ausentes)
        return None


    informacoes = variaveis_preparadas.get(variavel,
        {
            "Bloco": "Não informado",
            "Origem": "Não informada",
        },
    ) # caso a variavel n exista ele retorna o bloco e origem não informados


    base_inicial = dados[colunas_necessarias].copy()

    base_inicial["Diagnóstico binário"] = pd.to_numeric(base_inicial["Diagnóstico binário"], errors="coerce")

    base_inicial["Peso"] = pd.to_numeric(base_inicial["Peso"], errors="coerce")

    resposta_valida = base_inicial[variavel].notna()

    diagnostico_valido = base_inicial["Diagnóstico binário"].isin([0, 1])

    peso_valido = (base_inicial["Peso"].notna() & (base_inicial["Peso"] > 0))

    base = base_inicial[resposta_valida & diagnostico_valido & peso_valido].copy()

    if base.empty: #esta vazio?
        return None

    total_registros = len(base_inicial)
    registros_validos = len(base)

    populacao_total_estimada = base["Peso"].sum()

    base["Peso com diagnóstico"] = (base["Peso"] * base["Diagnóstico binário"])

    base["Peso sem diagnóstico"] = (base["Peso"]* (1 - base["Diagnóstico binário"]))

    populacao_com_diagnostico = (base["Peso com diagnóstico"].sum())

    prevalencia_geral = (populacao_com_diagnostico / populacao_total_estimada * 100)

    resumo = (base.groupby(variavel,observed=True).agg(
            Quantidade_de_participantes=(
                variavel,
                "size",
            ),
            Participantes_com_diagnostico=(
                "Diagnóstico binário",
                "sum",
            ),
            Populacao_estimada=(
                "Peso",
                "sum",
            ),
            Populacao_estimada_com_diagnostico=(
                "Peso com diagnóstico",
                "sum",
            ),
            Populacao_estimada_sem_diagnostico=(
                "Peso sem diagnóstico",
                "sum",
            ),
        )
        .reset_index()
        .rename(
            columns={variavel: "Categoria"}
        )
    )

    resumo["Participantes_com_diagnostico"] = (resumo["Participantes_com_diagnostico"].round().astype(int))

    resumo["Participantes_sem_diagnostico"] = (resumo["Quantidade_de_participantes"] - resumo["Participantes_com_diagnostico"])

    resumo["Percentual_da_amostra (%)"] = (resumo["Quantidade_de_participantes"] / registros_validos * 100)

    resumo["Proporcao_da_populacao (%)"] = (resumo["Populacao_estimada"] / populacao_total_estimada * 100)

    resumo["Com_depressao_na_categoria (%)"] = (resumo["Populacao_estimada_com_diagnostico"] / resumo["Populacao_estimada"] * 100)

    resumo["Sem_depressao_na_categoria (%)"] = (resumo["Populacao_estimada_sem_diagnostico"] / resumo["Populacao_estimada"] * 100)

    resumo["Diferenca_da_media_geral (p.p.)"] = (resumo["Com_depressao_na_categoria (%)"] - prevalencia_geral)

    colunas_tabela = [
        "Categoria",
        "Quantidade_de_participantes",
        "Percentual_da_amostra (%)",
        "Participantes_com_diagnostico",
        "Participantes_sem_diagnostico",
        "Populacao_estimada",
        "Proporcao_da_populacao (%)",
        "Com_depressao_na_categoria (%)",
        "Sem_depressao_na_categoria (%)",
    ]

    tabela_resumo = resumo[colunas_tabela].copy()

    contagem = pd.crosstab(base[variavel], base["Diagnóstico de depressão"])

    teste = {
        "Variável": variavel,
        "Participantes válidos": registros_validos,
        "Número de categorias": contagem.shape[0],
        "Qui-quadrado": np.nan,
        "Graus de liberdade": np.nan,
        "p-valor": np.nan,
        "V de Cramér": np.nan,
        "Células esperadas menores que 5": np.nan,
    }

    if (contagem.shape[0] >= 2 and contagem.shape[1] >= 2):
        chi2, p_valor, gl, esperadas = (chi2_contingency(contagem))

        n = contagem.to_numpy().sum()

        menor_dimensao = min(contagem.shape[0] - 1, contagem.shape[1] - 1)

        if n > 0 and menor_dimensao > 0:
            v_cramer = np.sqrt(chi2 / (n * menor_dimensao))
        else:
            v_cramer = np.nan

        teste.update({
            "Qui-quadrado": chi2,
            "Graus de liberdade": gl,
            "p-valor": p_valor,
            "V de Cramér": v_cramer,
            "Células esperadas menores que 5": int(
                (esperadas < 5).sum()
            ),
        })

    qualidade = pd.DataFrame({
        "Informação": [
            "Total de registros disponíveis",
            "Registros válidos usados",
            "Registros não utilizados",
            "Percentual de registros utilizados",
            "População total estimada",
        ],
        "Valor": [
            total_registros,
            registros_validos,
            total_registros - registros_validos,
            registros_validos / total_registros * 100,
            populacao_total_estimada,
        ],
    })

    print("=" * 78)
    print("ANÁLISE DA VARIÁVEL")
    print("=" * 78)

    print(f"Variável: {variavel}")
    print(f"Bloco: {informacoes['Bloco']}")
    print("Variável original da PNS:", informacoes["Origem"])
    print("Quantidade de categorias:", len(resumo))

    print("\nINFORMAÇÕES GERAIS")
    display(qualidade.round(2))

    print("\nRESUMO POR CATEGORIA")
    display(tabela_resumo.sort_values("Com_depressao_na_categoria (%)", ascending=False ).round(2))

    print("\nTABELA DE CONTAGEM")
    display(contagem)

    print("\nTESTE DE ASSOCIAÇÃO")
    display(pd.DataFrame([teste]).round(4))

    if mostrar_graficos:
        altura = max(4, resumo["Categoria"].nunique() * 0.48)


        grafico_proporcao = resumo.sort_values("Proporcao_da_populacao (%)", ascending=True)

        figura, eixo = plt.subplots(figsize=(10, altura))

        barras = eixo.barh(grafico_proporcao["Categoria"].astype(str), grafico_proporcao["Proporcao_da_populacao (%)"])

        eixo.set_title(f"Proporção da população por {variavel}")

        eixo.set_xlabel("Proporção da população válida (%)")

        eixo.set_ylabel(variavel)

        eixo.bar_label(barras, fmt="%.1f%%", padding=3)

        figura.tight_layout()
        plt.show()


        grafico_depressao = resumo.sort_values("Com_depressao_na_categoria (%)", ascending=True)

        figura, eixo = plt.subplots(figsize=(10, altura))

        barras = eixo.barh(grafico_depressao["Categoria"].astype(str), grafico_depressao["Com_depressao_na_categoria (%)"])

        eixo.axvline(prevalencia_geral, linestyle="--", label=(f"Prevalência geral: " f"{prevalencia_geral:.1f}%"))

        eixo.set_title(f"Percentual com depressão por {variavel}")

        eixo.set_xlabel("Percentual com diagnóstico de depressão (%)")

        eixo.set_ylabel(variavel)

        eixo.bar_label(barras, fmt="%.1f%%", padding=3)

        eixo.legend()

        figura.tight_layout()
        plt.show()

    return {
        "qualidade": qualidade,
        "resumo": tabela_resumo,
        "contagem": contagem,
        "teste": pd.DataFrame([teste]),
        "prevalencia_geral": prevalencia_geral,
    }

In [ ]:
variavel_escolhida = "Quintil de renda"

resultado_variavel_escolhida = analisar_variavel_completa(
    dados_descritivos,
    variavel_escolhida,
    variaveis_preparadas,
)

# Arvore

In [104]:
variaveis_por_tipo = {
    'Qualitativo Nominal': [
        'A001', 'A002010', 'A003010', 'A004010', 'A005010', 'A00601', 'A009010', 'A01501',
        'A016010', 'A01901', 'B001', 'C004', 'C006', 'C009', 'C01001', 'C011',
        'D001', 'E001', 'E02801', 'E02802', 'E02803', 'E02804', 'E02805', 'E02806',
        'E030', 'E03101', 'E03102', 'E03103', 'E03104', 'E03105', 'E03106', 'E03107',
        'E03108', 'E032', 'H003', 'H004', 'I00101', 'I00102', 'J002', 'J007',
        'J009', 'J014', 'J046', 'N004', 'N005', 'P046', 'P07004', 'P07005',
        'P07006', 'P07007', 'Q00201', 'Q03001', 'Q060', 'Q068', 'Q074', 'Q079',
        'Q084', 'Q088', 'Q11006', 'Q11007', 'Q11008', 'Q11009', 'Q11010', 'Q11405',
        'Q11406', 'Q11408', 'Q120', 'Q124', 'Q132', 'Q134', 'T001', 'T002',
        'T003', 'T004', 'U02501', 'V0001', 'V00201', 'V00202', 'V00203', 'V00204',
        'V00205', 'V0026', 'V0031', 'V01401', 'V01402', 'V01403', 'V01404', 'V01405',
        'V02701', 'V02702', 'V02801', 'V02802', 'V03502'
    ],

    'Quantitativo Discreto': [
        'A01001', 'A01401', 'C001', 'C008', 'P00104', 'P00404', 'P006', 'P00901',
        'P01101', 'P013', 'P015', 'P01601', 'P018', 'P02001', 'P02002', 'P023',
        'P02501', 'P02602', 'Q111', 'Q133', 'VDC003', 'VDF003'
    ],

    'EXCLUIR': [
        'A005012', 'A011', 'A01402', 'A01403', 'A018011', 'A018012', 'A018013', 'A018014',
        'A018015', 'A018016', 'A018017', 'A018018', 'A018019', 'A018020', 'A018021', 'A018022',
        'A018023', 'A018024', 'A018025', 'A018026', 'A018027', 'A018028', 'A02101', 'A02102',
        'A02201', 'A02305', 'A02306', 'A02307', 'A02308', 'A02401', 'A02402', 'B002',
        'B003', 'C00301', 'C00701', 'C00702', 'C00703', 'C010010', 'C012', 'C013',
        'C014', 'C015', 'C016', 'C017', 'C018', 'C01801', 'D00201', 'D00202',
        'D00301', 'D00501', 'D006', 'D00601', 'D007', 'D008', 'D00901', 'D010',
        'D01101', 'D01201', 'D01301', 'D01302', 'D01303', 'D014', 'D015', 'E002',
        'E003', 'E004', 'E005', 'E006011', 'E008', 'E010010', 'E010011', 'E010012',
        'E010013', 'E011', 'E01201', 'E01401', 'E014011', 'E01402', 'E01403', 'E01501',
        'E01601', 'E01602', 'E01603', 'E01604', 'E01605', 'E017', 'E01801', 'E01802',
        'E01803', 'E01804', 'E01805', 'E019', 'E022', 'E023011', 'E024011', 'E02402',
        'E024021', 'E025', 'E02501', 'E02502', 'E02503', 'E026', 'E02601', 'E027',
        'E033', 'F001011', 'F001021', 'F007011', 'F007021', 'F008011', 'F008021', 'F016',
        'G032', 'G033', 'G034', 'G035', 'G036', 'G038', 'G039', 'G040',
        'G041', 'G042', 'G044', 'G046', 'G047', 'G048', 'G049', 'G050',
        'G051', 'G052', 'G053', 'G054', 'G055', 'G057', 'G058', 'G05801',
        'G059', 'G060', 'G061', 'G062', 'G063', 'G064', 'G065', 'G066',
        'G067', 'G068', 'G070', 'G071', 'G072', 'G073', 'G074', 'G075',
        'G076', 'G077', 'G079', 'G080', 'G081', 'G082', 'G083', 'G084',
        'G085', 'G086', 'H001', 'H002', 'H005', 'H006', 'H007', 'H008',
        'H009', 'H010', 'H011', 'H012', 'H013', 'H014', 'H015', 'H016',
        'H017', 'H018', 'H019', 'H020', 'H021', 'H022', 'H023', 'H024',
        'H025', 'H026', 'H027', 'H028', 'H029', 'H030', 'I001021', 'I00103',
        'I001031', 'I004', 'I00401', 'I00402', 'I00403', 'I00404', 'I005', 'I006',
        'I010010', 'I012', 'J001', 'J003', 'J00402', 'J00404', 'J005', 'J006',
        'J00801', 'J01002', 'J012', 'J01502', 'J01602', 'J01701', 'J01802', 'J019',
        'J02002', 'J021', 'J022010', 'J023', 'J024', 'J025', 'J026', 'J02702',
        'J02901', 'J03001', 'J03102', 'J032', 'J03301', 'J034', 'J035', 'J03602',
        'J037', 'J038', 'J039', 'J04001', 'J04002', 'J041', 'J042', 'J043',
        'J044', 'J047', 'J048', 'J049', 'J051', 'J052', 'J05301', 'J054010',
        'J05402', 'J05403', 'J05404', 'J05405', 'J05406', 'J05407', 'J05408', 'J05409',
        'J056', 'J057', 'J060', 'K001', 'K004', 'K007', 'K010', 'K013',
        'K016', 'K019', 'K01901', 'K02001', 'K02101', 'K02102', 'K022', 'K025',
        'K028', 'K031', 'K034', 'K03401', 'K03501', 'K03601', 'K03602', 'K04301',
        'K04302', 'K04401', 'K045', 'K046', 'K047', 'K048', 'K050', 'K051',
        'K052', 'K05302', 'K05401', 'K05402', 'k055', 'K05601', 'K05602', 'K062',
        'L01701', 'L01702', 'L01703', 'L01704', 'L01705', 'L01706', 'L01707', 'L01708',
        'L01709', 'L01710', 'L01711', 'L01712', 'L01713', 'L01714', 'L01715', 'L01716',
        'L018', 'L019', 'L021', 'L022', 'L023', 'L024', 'L025', 'L026',
        'L027', 'L028', 'L029', 'L030', 'L031', 'L032', 'L033', 'L034',
        'L035', 'L036', 'L037', 'L038', 'L039', 'L040', 'L042', 'M001',
        'M002', 'M00203', 'M00302', 'M00303', 'M00401', 'M00402', 'M005010', 'M005011',
        'M00601', 'M007', 'M008', 'M009', 'M01001', 'M011011', 'M011021', 'M011031',
        'M011041', 'M011051', 'M011061', 'M011071', 'N006', 'N00701', 'N008', 'N010',
        'N011', 'N012', 'N013', 'N014', 'N015', 'N016', 'N017', 'N018',
        'O00101', 'O00201', 'O00401', 'O00402', 'O00501', 'O00701', 'O00801', 'O00802',
        'O00803', 'O009', 'O00901', 'O010', 'O01102', 'O01401', 'O01501', 'O01602',
        'O01702', 'O019', 'O02001', 'O021', 'O02101', 'O02201', 'O023', 'O02401',
        'P00102', 'P00103', 'P00201', 'P00402', 'P00403', 'P00405', 'P005', 'P00601',
        'P00602', 'P00603', 'P00604', 'P00605', 'P00607', 'P00608', 'P00609', 'P00610',
        'P00611', 'P00612', 'P00613', 'P00614', 'P00615', 'P00616', 'P00617', 'P00618',
        'P00619', 'P00620', 'P00621', 'P00622', 'P00623', 'P01001', 'P019', 'P02101',
        'P02102', 'P02401', 'P02601', 'P027', 'P02801', 'P029', 'P03001', 'P03201',
        'P03202', 'P03301', 'P03302', 'P03303', 'P034', 'P035', 'P036', 'P03701',
        'P03702', 'P038', 'P039', 'P03904', 'P03905', 'P03906', 'P040', 'P04001',
        'P04101', 'P04102', 'P042', 'P04301', 'P04302', 'P044', 'P04401', 'P04405',
        'P04406', 'P04701', 'P04801', 'P04902', 'P051', 'P053', 'P05401', 'P05402',
        'P05403', 'P05404', 'P05405', 'P05406', 'P05407', 'P05408', 'P05409', 'P05410',
        'P05411', 'P05412', 'P05413', 'P05414', 'P05415', 'P05416', 'P05417', 'P05418',
        'P05419', 'P05421', 'P05422', 'P055', 'P056', 'P05601', 'P05602', 'P05603',
        'P05604', 'P05605', 'P057', 'P058', 'P05801', 'P05802', 'P05901', 'P05902',
        'P05903', 'P05904', 'P05905', 'P05906', 'P060', 'P06101', 'P06102', 'P06103',
        'P06104', 'P06105', 'P06106', 'P06302', 'P067', 'P06701', 'P069', 'P06901',
        'P07101', 'P07201', 'Q00202', 'Q003', 'Q00401', 'Q00502', 'Q00503', 'Q00601',
        'Q00602', 'Q00801', 'Q009', 'Q010', 'Q01101', 'Q01202', 'Q014', 'Q015',
        'Q016', 'Q017', 'Q018010', 'Q018011', 'Q018012', 'Q018013', 'Q018014', 'Q018015',
        'Q018016', 'Q018017', 'Q01910', 'Q019101', 'Q01911', 'Q019111', 'Q01912', 'Q019121',
        'Q01913', 'Q019131', 'Q022', 'Q02301', 'Q026', 'Q02701', 'Q028', 'Q02901',
        'Q03002', 'Q031', 'Q03201', 'Q03302', 'Q03303', 'Q03403', 'Q03404', 'Q03601',
        'Q03701', 'Q03801', 'Q03802', 'Q03803', 'Q03804', 'Q03805', 'Q03806', 'Q03807',
        'Q03901', 'Q04002', 'Q042', 'Q043', 'Q044', 'Q045', 'Q046011', 'Q046012',
        'Q046013', 'Q046014', 'Q046015', 'Q046016', 'Q046017', 'Q046018', 'Q046019', 'Q046020',
        'Q046021', 'Q04707', 'Q047071', 'Q04708', 'Q047081', 'Q04709', 'Q047091', 'Q04710',
        'Q047101', 'Q04711', 'Q047111', 'Q050', 'Q05101', 'Q05301', 'Q05401', 'Q055011',
        'Q055012', 'Q055013', 'Q055014', 'Q055015', 'Q055016', 'Q056', 'Q05701', 'Q058',
        'Q05901', 'Q061', 'Q06207', 'Q06208', 'Q06209', 'Q06210', 'Q06211', 'Q06212',
        'Q06306', 'Q06307', 'Q06308', 'Q06309', 'Q06310', 'Q06311', 'Q064', 'Q06506',
        'Q06507', 'Q06508', 'Q06509', 'Q06601', 'Q067', 'Q070', 'Q07208', 'Q07209',
        'Q07210', 'Q07211', 'Q07212', 'Q07213', 'Q073', 'Q075', 'Q076', 'Q07601',
        'Q07704', 'Q07705', 'Q07706', 'Q07707', 'Q07708', 'Q07709', 'Q07710', 'Q07711',
        'Q078', 'Q080', 'Q08107', 'Q08108', 'Q08109', 'Q08110', 'Q08111', 'Q082',
        'Q083', 'Q085', 'Q08607', 'Q08608', 'Q08609', 'Q08610', 'Q08611', 'Q087',
        'Q08901', 'Q09007', 'Q09008', 'Q09009', 'Q09010', 'Q09011', 'Q091', 'Q092',
        'Q09201', 'Q09202', 'Q09301', 'Q094', 'Q09502', 'Q09605', 'Q09606', 'Q09607',
        'Q098', 'Q100', 'Q10101', 'Q10202', 'Q104', 'Q105', 'Q106', 'Q10701',
        'Q109', 'Q11201', 'Q11407', 'Q115', 'Q11604', 'Q11605', 'Q11606', 'Q11607',
        'Q11701', 'Q11806', 'Q11807', 'Q11808', 'Q11809', 'Q119', 'Q121010', 'Q121011',
        'Q121012', 'Q121013', 'Q121014', 'Q121015', 'Q121016', 'Q12102', 'Q12103', 'Q12104',
        'Q12105', 'Q12106', 'Q12107', 'Q12108', 'Q12109', 'Q12201', 'Q12301', 'Q125',
        'Q12501', 'Q12607', 'Q12608', 'Q12609', 'Q12610', 'Q127', 'Q128', 'R00101',
        'R002010', 'R004', 'R005', 'R00601', 'R007', 'R008', 'R009010', 'R010',
        'R011', 'R012', 'R013', 'R014', 'R015', 'R01701', 'R019', 'R020',
        'R02101', 'R022', 'R023', 'R02402', 'R025', 'R026', 'R027', 'R028',
        'R029', 'R030', 'R031', 'R032', 'R033', 'R034', 'R035', 'R03601',
        'R03602', 'R03603', 'R03604', 'R03605', 'R03606', 'R03607', 'R03608', 'R03609',
        'R03610', 'R03611', 'R037', 'R038', 'S065', 'S066', 'S06701', 'S06702',
        'S06703', 'S068', 'S06901', 'S06902', 'S070', 'S071', 'S072', 'S073',
        'S074', 'S075', 'S076', 'S077', 'S07901', 'S07902', 'S07903', 'S07904',
        'S07905', 'S080', 'S081', 'S082', 'S083', 'S084', 'S085', 'S086',
        'S087', 'S088', 'S089', 'S090', 'S091', 'S092', 'S095', 'S096',
        'S097', 'S098', 'S099', 'S09901', 'S109', 'S110', 'S11001', 'S111',
        'S112', 'S113', 'S114', 'S115', 'S116', 'S117', 'S118', 'S11801',
        'S119', 'S120', 'S121', 'S122', 'S123', 'S124', 'S125', 'S126',
        'S127', 'S128', 'S129', 'S130', 'S131', 'S132', 'S133', 'S134',
        'S135', 'S136', 'S137', 'S138', 'S139', 'T005', 'T00601', 'T00602',
        'T00603', 'T00604', 'T00605', 'T00606', 'U00204', 'U00205', 'U00206', 'U00207',
        'U00208', 'U00902', 'U01002', 'U014', 'U02001', 'U02101', 'U02303', 'U02403',
        'UPA_PNS', 'V0006_PNS', 'V001', 'V00101', 'V0015', 'V0020', 'V0022', 'V0024',
        'V0025A', 'V0025B', 'V0028', 'V00281', 'V00282', 'V00283', 'V0029', 'V00291',
        'V00292', 'V00293', 'V003', 'V0030', 'V00301', 'V00302', 'V00303', 'V006',
        'V007', 'V015', 'V018', 'V019', 'V029', 'V032', 'V033', 'V034',
        'V03501', 'V03503', 'V036', 'V037', 'V038', 'V039', 'VDC001', 'VDDATA',
        'VDE001', 'VDE002', 'VDE014', 'VDF001', 'VDF00102', 'VDF002', 'VDF004', 'VDL001',
        'VDM001', 'VDP001', 'VDR001', 'W001', 'W00101', 'W00102', 'W00103', 'W00201',
        'W00202', 'W00203', 'Y001', 'Y00101', 'Y002', 'Y003', 'Y004', 'Y005',
        'Y006', 'Y007', 'Z001', 'Z00101', 'Z00102', 'Z002', 'Z003', 'Z004',
        'Z005', 'Z006', 'Z007', 'Z008', 'Z009', 'Z010', 'Z011', 'Z012',
        'Z013', 'Z01401', 'Z01402'
    ],

    'Qualitativo Ordinal': [
        'B004', 'J00101', 'J01101', 'J01301', 'M01401', 'M01501', 'M01601', 'M01701',
        'M01801', 'M01901', 'N001', 'N00101', 'P04501', 'P04502', 'P050', 'P052',
        'P068', 'Q00101', 'U00101', 'U00401', 'U005', 'U006', 'U02302', 'U02402',
        'VDD004A'
    ]
}

In [105]:
import optuna

from optuna.samplers import TPESampler

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    ConfusionMatrixDisplay,
    f1_score,
    make_scorer,
    precision_score,
    PrecisionRecallDisplay,
    recall_score,
    roc_auc_score,
    RocCurveDisplay,
)
from sklearn.model_selection import (
    StratifiedKFold,
    cross_val_predict,
    cross_val_score,
    cross_validate,
    train_test_split,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier

SEED = 42

In [106]:
# y = variável que queremos prever
# Q092: 1 = com diagnóstico de depressão / 2 = sem diagnóstico
y = base_adultos["Q092"].map({1: 1, 2: 0})

# X = variáveis que serão usadas para prever y
# Usa a mesma lista EXCLUIR que você já montou no notebook
X = base_adultos.drop(
    columns=variaveis_por_tipo["EXCLUIR"]
).copy()

# Mantém apenas linhas em que Q092 possui resposta válida
linhas_validas = y.notna()
X = X.loc[linhas_validas].copy()
y = y.loc[linhas_validas].astype(int).copy()

# Separa os tipos de variáveis que realmente ficaram em X
variaveis_nominais = [
    coluna
    for coluna in variaveis_por_tipo["Qualitativo Nominal"]
    if coluna in X.columns
]

variaveis_numericas = [
    coluna
    for coluna in (
        variaveis_por_tipo["Quantitativo Discreto"]
        + variaveis_por_tipo["Qualitativo Ordinal"]
    )
    if coluna in X.columns
]

print("Formato de X:", X.shape)
print("Formato de y:", y.shape)
print("Nominais:", len(variaveis_nominais))
print("Discretas + ordinais:", len(variaveis_numericas))

print("\nDistribuição de y:")
print(y.value_counts())

Formato de X: (88531, 140)
Formato de y: (88531,)
Nominais: 93
Discretas + ordinais: 47

Distribuição de y:
Q092
0    80289
1     8242
Name: count, dtype: int64

In [107]:
qtd = X.isna().sum()
lista_faltantes = [(coluna, quantidade) for coluna, quantidade in qtd.items() if quantidade > 0]

print(lista_faltantes)

[('A01501', 1302), ('E02801', 14646), ('E02802', 14646), ('E02803', 14646), ('E02804', 14646), ('E02805', 14646), ('E02806', 14646), ('N004', 1889), ('N005', 1889), ('P00104', 853), ('P00404', 853), ('P052', 11286), ('Q00201', 1669), ('Q03001', 6182), ('Q060', 7280), ('Q11007', 83739), ('Q11008', 83739), ('Q11009', 83739), ('Q11010', 83739), ('Q111', 83739), ('Q11405', 83739), ('Q11406', 83739), ('Q11408', 83739), ('Q133', 80833), ('Q134', 80833), ('U00101', 1458), ('U00401', 1458), ('U02501', 20612), ('V02801', 672), ('V02802', 672), ('V03502', 73209), ('H003', 61999), ('H004', 61999), ('VDF003', 22)]

In [108]:
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=SEED,
)

print("Treino:", X_treino.shape)
print("Teste:", X_teste.shape)

print("\nPercentual de depressão no treino:")
print(f"{y_treino.mean() * 100:.2f}%")

print("\nPercentual de depressão no teste:")
print(f"{y_teste.mean() * 100:.2f}%")

Treino: (70824, 140)
Teste: (17707, 140)

Percentual de depressão no treino:
9.31%

Percentual de depressão no teste:
9.31%

In [109]:
# Fazemos cópias para não alterar X_treino e X_teste originais
X_treino_preenchido = X_treino.copy()
X_teste_preenchido = X_teste.copy()


# ---------------------------------------------------------
# 1. DISCRETAS E ORDINAIS -> MEDIANA
# ---------------------------------------------------------

faltantes_mediana = [
    coluna
    for coluna in (
        variaveis_por_tipo["Quantitativo Discreto"]
        + variaveis_por_tipo["Qualitativo Ordinal"]
    )
    if coluna in X_treino.columns
]

# As medianas são calculadas SOMENTE com o treino
medianas = np.nanmedian(
    X_treino[faltantes_mediana],
    axis=0,
)

for j, coluna in enumerate(faltantes_mediana):
    X_treino_preenchido[coluna] = X_treino_preenchido[coluna].fillna(
        medianas[j]
    )

    # No teste usamos a mediana que veio do treino
    X_teste_preenchido[coluna] = X_teste_preenchido[coluna].fillna(
        medianas[j]
    )


# ---------------------------------------------------------
# 2. NOMINAIS -> MODA
# ---------------------------------------------------------

faltantes_nominais = [
    coluna
    for coluna in variaveis_por_tipo["Qualitativo Nominal"]
    if coluna in X_treino.columns
]

for coluna in faltantes_nominais:
    # A moda também é calculada SOMENTE com o treino
    moda = X_treino[coluna].mode()

    if not moda.empty:
        valor_moda = moda.iloc[0]

        X_treino_preenchido[coluna] = X_treino_preenchido[coluna].fillna(
            valor_moda
        )

        # No teste usamos a moda que veio do treino
        X_teste_preenchido[coluna] = X_teste_preenchido[coluna].fillna(
            valor_moda
        )


print("Faltantes no treino depois do preenchimento:")
print(X_treino_preenchido.isna().sum().sum())

print("\nFaltantes no teste depois do preenchimento:")
print(X_teste_preenchido.isna().sum().sum())

Faltantes no treino depois do preenchimento:
0

Faltantes no teste depois do preenchimento:
0

### depois eu vejo

In [ ]:
data = base_adultos.drop(variaveis_por_tipo["EXCLUIR"], axis = 1)
data = data.drop_duplicates()

In [ ]:
qtd = data.isna().sum()
lista_faltantes = list(qtd[qtd > 0].items())

print(lista_faltantes)

In [ ]:
data['A01001'].value_counts(dropna=False)

In [ ]:
display(data.shape)
display(data.head())

In [ ]:
faltantes = []
for i in (variaveis_por_tipo['Quantitativo Discreto'] + variaveis_por_tipo['Qualitativo Ordinal']):
    if i in [x[0] for x in lista_faltantes]:
        faltantes.append(i)

X = data[faltantes]
medianas = np.nanmedian(X, axis=0)

data_preenchida = data.copy()

for i in range(data_preenchida.shape[0]):
    for j in range(len(faltantes)):
        if np.isnan(data_preenchida.loc[data_preenchida.index[i], faltantes[j]]):
            data_preenchida.loc[data_preenchida.index[i], faltantes[j]] = medianas[j]

In [ ]:
faltantes = []

for i in variaveis_por_tipo['Qualitativo Nominal']:
    if i in [x[0] for x in lista_faltantes]:
        faltantes.append(i)


for coluna in faltantes:
    moda = data_preenchida[coluna].mode()

    if not moda.empty:
        data_preenchida[coluna] = data_preenchida[coluna].fillna(moda.iloc[0])

In [ ]:
display(data_preenchida.shape)
display(data_preenchida.head())